### ISSUE TITLE
how to use transform in useQuery?

### ISSUE THREAD

**Issue by dimasxp** [falcondev-oss/trpc-vue-query#4]
how to transform response before cache ?

**Comment by LouisHaftmann** [comment]
There currently is no built-in way to transform the response before caching. Instead, you could just create a composable that transforms the data like this:

```ts
export function useUserNames(){
  const query = useTRPC().users.list.useQuery()
  return {
    ...query,
    data: computed(() => query.data.value?.map(user => user.name))
  }
}
```

There also is a `select` query option:
```ts
useTRPC().users.list.useQuery(undefined, {
  select: (users) => users.map(user => user.name)
})
```

**Comment by dimasxp** [comment]
Got it, thanks for the good examples and this wrapper. very handy and useful 👏
